CREATE TABLE laptops (
    Id INTEGER PRIMARY KEY,
    Company TEXT,
    Product TEXT,
    TypeName TEXT,
    Inches REAL,
    Ram INTEGER,
    OS TEXT,
    Weight REAL,
    Price_euros REAL,
    Screen TEXT,
    ScreenW INTEGER,
    ScreenH INTEGER,
    Touchscreen TEXT,
    IPSpanel  TEXT,
    RetinaDisplay  TEXT,
    CPU_company TEXT,
    CPU_freq REAL,
    CPU_model TEXT,
    PrimaryStorage INTEGER,
    SecondaryStorage INTEGER,
    PrimaryStorageType TEXT,
    SecondaryStorageType TEXT,
    GPU_company TEXT,
    GPU_model TEXT
)